FROM node:18-alpine AS build
WORKDIR /angular.front.b2b-take-home
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build:ui
RUN npm run postbuild:ui
RUN npm run prebuild:app
RUN npm run build:app

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /angular.front.b2b-take-home/dist/b2b-take-home-app/browser /usr/share/nginx/html

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]
